import { UserContext } from "@/context/UserContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserContext.Provider value={null}>
        <body>{children}</body>
      </UserContext.Provider>
    </html>
  );
}
