import { useState } from "react";
import { UserContext } from "@/context/UserContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [user, setUser] = useState(null);

  return (
    <html lang="en">
      <UserContext.Provider value={{ user, setUser }}>
        <body>{children}</body>
      </UserContext.Provider>
    </html>
  );
}
